defaultSemverRangePrefix: ""

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: warning

nodeLinker: node-modules

packageExtensions:
  "@labelflow/web@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
      "@babel/core": "*"
  "@chakra-ui/accordion@1.3.6":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/anatomy@1.0.0":
    peerDependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/skeleton@1.1.18":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/storybook-addon@*":
    peerDependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/switch@1.2.9":
    peerDependencies:
      framer-motion: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      "react": "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/csf-tools@*":
    peerDependencies:
      "@babel/core": "*"
  eslint-config-airbnb-typescript@12.3.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  next@*:
    peerDependencies:
      "webpack": "*"
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  realistic-structured-clone@2.0.2:
    dependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  next-auth@*:
    peerDependencies:
      "@prisma/client": "*"
  graphiql@*:
    peerDependencies:
      graphql-ws: "*"
      typescript: "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  graphql-language-service-interface@*:
    peerDependencies:
      typescript: "*"
  graphql-language-service-types@*:
    peerDependencies:
      typescript: "*"
  graphql-language-service-parser@*:
    peerDependencies:
      typescript: "*"
  graphql-language-service-utils@*:
    peerDependencies:
      typescript: "*"
  graphql-language-service@*:
    peerDependencies:
      typescript: "*"
  codemirror-graphql@*:
    peerDependencies:
      typescript: "*"
  apollo-link-context@*:
    peerDependencies:
      graphql: "*"
  apollo-link-error@*:
    peerDependencies:
      graphql: "*"
  apollo-language-server@*:
    peerDependencies:
      typescript: "*"
  apollo-codegen-core@*:
    peerDependencies:
      typescript: "*"
  apollo-codegen-flow@*:
    peerDependencies:
      typescript: "*"
  apollo-codegen-scala@*:
    peerDependencies:
      typescript: "*"
  apollo-codegen-swift@*:
    peerDependencies:
      typescript: "*"
  apollo-codegen-typescript@*:
    peerDependencies:
      typescript: "*"
  apollo@*:
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
